# Generated by Django 5.0.6 on 2025-04-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_remove_patient_hospital_remove_patient_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_deleted_by_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_deleted_by_patient',
            field=models.BooleanField(default=False),
        ),
    ]
