# Generated by Django 5.0.6 on 2025-04-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_appointment_is_deleted_by_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
